---
- name: Set primary user shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: True
  ignore_errors: True

- name: Create dotfiles directory
  file:
    path: "{{ dotfiles_target_dir }}"
    state: directory

- name: Setup dotfiles directory structure
  file:
    path: "{{ dotfiles_target_dir }}/{{ item.path }}"
    state: directory
  with_filetree:
    - ../templates
  when: item.state == 'directory'

- name: Copy dotfiles
  template:
    src: "{{ item.path }}"
    dest: "{{ dotfiles_target_dir }}/{{ item.path }}"
  with_filetree:
    - ../templates
  when: item.state == 'file'

- name: Obtain file stats for dotfile symlinks
  stat:
    path: "{{ ansible_env.HOME }}/.{{ item }}"
  with_items: "{{ dotfiles_symlinks }}"
  register: dotfiles_dirs

- name: Setup dotfiles symlinks target directory structure
  file:
    path: "{{ item.path }}"
    state: directory
  when: item.stat.isdir is defined and item.stat.isdir
  with_items: "{{ dotfiles_dirs.results }}"

- name: Symlink dotfiles
  file:
    state: link
    force: yes
    src: "{{ dotfiles_target_dir }}/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
  with_items: "{{ dotfiles_symlinks }}"

- name: Create zgen directory
  file:
    path: "{{ ansible_env.HOME }}/.zgen"
    state: directory

- name: Install zgen
  git:
    repo: https://github.com/tarjoilija/zgen.git
    dest: "{{ ansible_env.HOME }}/.zgen"

- name: Create Vim target directory
  file:
    path: "{{ vim_target_dir }}/autoload"
    state: directory

- name: Download vim-plug in Vim target directory
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ vim_target_dir }}/autoload/plug.vim"

- name: Install Vim plugins
  shell: vim -E -s -c "source ~/.vimrc" -c PlugInstall -c qa
  args:
    executable: /bin/zsh
  ignore_errors: yes

- name: Create Tmux plugins directory
  file:
    path: "{{ tmux_target_dir }}/plugins"
    state: directory

- name: Install Tmux Plugin Manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tmux_target_dir }}/plugins/tpm"

- name: Install Tmux Plugin Manager plugins
  shell: "{{ tmux_target_dir }}/plugins/tpm/scripts/install_plugins.sh"

