---
- name: Create Vim target directory
  file:
    path: "{{ vim_path }}/autoload"
    state: directory

- name: Download vim-plug in Vim target directory
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ vim_path }}/autoload/plug.vim"

- name: Install Vim plugins
  shell: vim -E -s -c "source ~/.vimrc" -c PlugInstall -c qa
  args:
    executable: /bin/zsh
  ignore_errors: yes
