# vim:syntax=sh

# The order in which these files are loaded is the following:
# - /etc/zshenv
# - ~/.zshenv
# - /etc/zprofile
# - ~/.zprofile
# - /etc/zshrc
# - ~/.zshrc

# Since /etc/zshenv does not exist, we load the initial paths using path_helper
# If PATH_HELPER_EXECUTED is defined, it means that path_helper was already
# executed
if [[ -x /usr/libexec/path_helper && -z $PATH_HELPER_EXECUTED ]]; then
  eval `/usr/libexec/path_helper -s`
  export PATH_HELPER_EXECUTED=true
fi

#######
# ENV #
#######
export XDG_CONFIG_HOME={{ xdg_config_home }}
export XDG_CACHE_HOME={{ xdg_cache_home }}
export XDG_DATA_HOME={{ xdg_data_home }}

# Less Colors for Man Pages
# http://linuxtidbits.wordpress.com/2009/03/23/less-colors-for-man-pages/
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# Set the TMPDIR explicitly in order to make sure we can use the same
# Tmux socket when connecting to the workstation through SSH
# http://stackoverflow.com/questions/9039256/tmux-not-re-attaching
export TMPDIR=/tmp

# Use vim as an editor
export EDITOR=vim

# enable colored output from ls, etc
export CLICOLOR=1

# Jupyter config directory
export JUPYTER_CONFIG_DIR=$XDG_CONFIG_HOME/jupyter

########
# PATH #
########
# HOMEBREW PATH
if [[ ":$PATH:" != *":{{ homebrew_bin_path }}:"* ]]; then
  PATH={{ homebrew_bin_path }}:$PATH
fi
if [[ ":$PATH:" != *":{{ homebrew_path }}/sbin:"* ]]; then
  PATH={{ homebrew_path }}/sbin:$PATH
fi

# GO PATH
if [[ ":$PATH:" != *":$HOME/go/bin:"* ]]; then
  PATH=$PATH:$HOME/go/bin
fi

# GLOUD PATH
if [[ ":$PATH:" != *":$HOME/.google-cloud-sdk/bin:"* ]]; then
  PATH=$PATH:$HOME/.google-cloud-sdk/bin
fi

# PYENV - Lazy loaded
pyenv() {
  eval "$(command pyenv init -)"
  pyenv "$@"
}

# JENV
if [[ ":$PATH:" != *":$HOME/.jenv/shims:"* ]]; then
  eval "$(jenv init - --no-rehash)"
  (jenv rehash &) 2> /dev/null
fi

# RUST
if [[ ":$PATH:" != *":$HOME/.cargo/bin:"* ]]; then
  PATH=$PATH:$HOME/.cargo/bin
fi

# CUSTOM SCRIPTS
if [[ ":$PATH:" != *":$XDG_DATA_HOME/bin:"* ]]; then
  PATH=$PATH:$XDG_DATA_HOME/bin
fi

export PATH

##########
# CONFIG #
##########
# Vi mode
bindkey -v
bindkey "^F" vi-cmd-mode
bindkey jj vi-cmd-mode

# Add some readline keys back
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line

# Handy keybindings
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word
bindkey -s "^T" "^[Isudo ^[A" # "t" for "toughguy"

# Automatically pushd
export dirstacksize=5

# Awesome cd movements from zshkit
setopt AUTOCD AUTOPUSHD PUSHDMINUS PUSHDSILENT PUSHDTOHOME
setopt cdablevars

# Enable extended globbing
setopt EXTENDED_GLOB

# UTF-8 terminal support
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Disable autocorrection
unsetopt CORRECT_ALL

# Syntax
if [[ -f {{ homebrew_path }}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
  source {{ homebrew_path }}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

#########
# ALIAS #
#########
alias ls='ls -laGFh'

# Git
alias gs='git status'
alias gl="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gg="git config user.email 'damselem@google.com'"

# Workspace
alias wws='cd ~/dev/waze'

# Copy the buit path so we can restore it in .zprofile after /etc/zprofile runs
export ZSH_ENV_PATH=$PATH
