# vim:syntax=sh

###############
# COMPLETIONS #
###############
# Load ZSH completion functions
fpath=({{ homebrew_path }}/share/zsh-completions $fpath)

# Completion
autoload -U compinit
compinit

# GCloud completions
if [[ -f ~/.google-cloud-sdk/completion.zsh.inc ]]; then
  source ~/.google-cloud-sdk/completion.zsh.inc
fi

###########
# HISTORY #
###########
HISTFILE=~/.zsh_history
SAVEHIST=10000
HISTSIZE=10000 # Keep TONS of history

setopt APPEND_HISTORY # Adds history
setopt INC_APPEND_HISTORY # Adds history incrementally
setopt SHARE_HISTORY # Share it across sessions
setopt HIST_IGNORE_ALL_DUPS # Don't record dupes in history
setopt HIST_REDUCE_BLANKS
setopt EXTENDED_HISTORY # Add timestamps to history

bindkey "^R" history-incremental-search-backward # use incremental search
bindkey "^P" history-search-backward

###########
# PLUGINS #
###########
source "${HOME}/.zgen/zgen.zsh"

if ! zgen saved; then
	zgen load "mafredri/zsh-async"
	zgen load "sindresorhus/pure"
	zgen load "vasyharan/zsh-brew-services"
	zgen load "zsh-users/zsh-syntax-highlighting"

	zgen load "zsh-users/zsh-completions"
	zgen load "felixr/docker-zsh-completion"

  zgen save
fi

##########
# CONFIG #
##########
# makes color constants available
autoload -U colors
colors

# Override pure prompt color
PROMPT='%(?.%F{green}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f '

# Initialize FZF settings
if [[ -f ~/.fzf.zsh ]]; then
  source ~/.fzf.zsh
fi
